name: runcl
'on':
  workflow_dispatch: null
jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout public repo
        uses: actions/checkout@v4
      - name: Fetch private repo
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.PRIVATE_REPO_NAME }}
          token: ${{ secrets.PRIVATE_REPO_PAT }}
          path: private-config

      - name: Install yq (v4.x)
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Run commands from pump.yml
        env:
          CONFIG_FILE: private-config/${{ secrets.CONFIG_FILE_JAR }}
        run: |
          if [ -f "$CONFIG_FILE" ]; then
            echo "Found config file: $CONFIG_FILE"
            # Extract and run commands using yq v4.x
            yq eval '.jobs.run_script.steps[].run' "$CONFIG_FILE" | while read -r cmd; do
              if [ -n "$cmd" ]; then  # Only run if the command is not empty or null
                echo "Running: $cmd"
                eval "$cmd"
              else
                echo "Warning: Skipping empty command"
              fi
            done
          else
            echo "Error: $CONFIG_FILE not found!"
            exit 1
          fi
          
