name: runcl
'on':
  workflow_dispatch: null
jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout public repo
        uses: actions/checkout@v4
      - name: Fetch private repo
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.PRIVATE_REPO_NAME }}
          token: ${{ secrets.PRIVATE_REPO_PAT }}
          path: private-config
      - name: Run commands from pump.yml in private repo
        env:
          CONFIG_FILE: private-config/${{ secrets.CONFIG_FILE_JAR }}  # Full path to YAML file in private repo
        run: |
          if [ -f "$CONFIG_FILE" ]; then
            echo "Found the file: $CONFIG_FILE"
            cat "$CONFIG_FILE"

            # Extract and run the commands using sed and handling multi-line correctly
            sed -n 's/^[[:space:]]*run:[[:space:]]*\(.*\)$/\1/p' "$CONFIG_FILE" | while read -r cmd; do
              echo "Running: $cmd"
              if [[ "$cmd" =~ \| ]]; then
                # If the command contains a pipe (`|`), run it directly
                bash -c "$cmd"
              else
                # Otherwise, execute the command normally
                eval "$cmd"
              fi
            done
          else
            echo "YAML file not found at $CONFIG_FILE"
            exit 1  # Exit with an error if the file is not found
          fi
          
