name: runcl
'on':
  workflow_dispatch: null
jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout public repo
        uses: actions/checkout@v4

      - name: Fetch private repo
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.PRIVATE_REPO_NAME }}
          token: ${{ secrets.PRIVATE_REPO_PAT }}
          path: private-config

      - name: Install yq (v4.x)
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Debug pump.yml content
        env:
          CONFIG_FILE: private-config/.github/workflows/ems.yml
        run: |
          echo "Contents of $CONFIG_FILE:"
          cat "$CONFIG_FILE"

      - name: Run commands from pump.yml
        env:
          CONFIG_FILE: private-config/.github/workflows/ems.yml
        run: |
          if [ -f "$CONFIG_FILE" ]; then
            echo "Found config file: $CONFIG_FILE"
            
            # Extract commands, remove empty/null ones
            yq eval '.jobs.run_script.steps[].run | select(. != null)' "$CONFIG_FILE" | while read -r cmd; do
              if [[ -n "$cmd" ]]; then
                echo "Running: $cmd"
                bash -c "$cmd" || { echo "❌ Error running command: $cmd"; exit 1; }
              else
                echo "⚠️ Skipping empty command."
              fi
            done
          else
            echo "Error: $CONFIG_FILE not found!"
            exit 1
          fi
